### ISSUE TITLE
ToDoList app submitted.

### ISSUE THREAD

**Issue by KarlClark** [KarlClark/cpToDoApp#1]
Diana, you don't really have to look at this.  It's just ToDo app with no added features. cc\ @CoderRed99

**Comment by CoderRed99** [comment]
Ok, You've got the licecap app already, right?



Warm regards,

Dianna

Extroverted Geek - ​Mobile ​Developer

**Comment by KarlClark** [comment]
Yes, I have licecap. Thanks for responding so I know I did the issue correctly. cc\  @CoderRed99
